### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by zaher-aa** [abdo-kotb/food-order-app#1]
### Hi Abdulrahman, I hope you're doing well
I think the app is not working. When I open the app, I get this page. I suppose that I should see the items that I can add to my cart, yet I can't do anything.
I hope you fix this problem.

![image](https://user-images.githubusercontent.com/78752405/153599305-8f24d9d4-449e-43e3-a130-bcb06c88d9a9.png)

**Comment by abdo-kotb** [comment]
Hi,

Thanks a lot for alerting me to the issue, I really appreciate that.

It looks like I had deleted the meals data from the backend server by mistake 😅
It should be working correctly now.

Thanks again,

**Comment by zaher-aa** [comment]
@abdo-kotb, yes its now working very well, great work.
Now you can close this issue.
